const path = require('path');

require('esbuild').build({
  entryPoints: [
    'actions/createPrNextCheckSuite.ts',
    'actions/notifyPreReleaseResult.ts',
    'actions/notifyPrNextResult.ts',
  ],
  outdir: path.join(__dirname, '../../scripts/github'),
  bundle: true,
  splitting: true,
  platform: 'node',
  format: 'esm',
  chunkNames: 'chunks/[name]-[hash]',
  target: 'node14',
  banner: {
    js: '// This file is generated by tools/github',
  },
  treeShaking: true,
});
