// This file is generated by tools/github
import { createVersionText } from './chunks/chunk-67TVDRNV.js';
import { call } from './chunks/chunk-N3B6LQIW.js';

// actions/notifyPreReleaseResult.ts
call(async ({ github, context, core }) => {
  const issueBody = createVersionText('Pre-Release', process.env.CURRENT_VERSION, context);
  await github.rest.issues.createComment({
    issue_number: context.issue.number,
    owner: context.repo.owner,
    repo: context.repo.repo,
    body: issueBody,
  });
});
