name: CHECK

on:
  workflow_dispatch:
  push:
    branches: [main, v*.*]
  pull_request:
    branches: [main, v*.*]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-2019]
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Build
        run: |
          yarn --prefer-offline
          npm run init
          npm run bundle:lite

      - name: Lint
        run: |
          npm run lint -- --quiet
